--1. Display the number of states present in the location table
select count(distinct(state)) from location;

--2. how many products are of regular type
select count(type) from  product
where type = 'Regular';

--3. How many spending has been done on marketing of product id=1
select productid, sum(marketing) as total_marketing from fact 
where productid = 1
group by productid;

--4. what is the minimun sales of product
select productid,min(sales) from fact
where productid = 1;

--5. Display the max COGS
select  max(cogs) from fact ;

--6. dispaly the details of the product where product type is coffee."""
select * from product
where Product_Type = 'Coffee';

--7. display the details where total expenses are greater then 40.
select productid,sum(TotalExpenses) from fact 
group by productid;

--8. average sales in area code 719.
select *  from location
where AreaCode = 719;

--9. find out the total profit generated by colorado state
select sum(f.profit),l.state from fact as f
left join location as l
on f.area_code = l.area_code
where state = 'colorado'
group by state;

--10. Display the average inventory for each productid.
select productid,avg(inventory) as avg_inventory from fact
group by productid
order by productid;

--11. display state in a squential order in a location table.
select * from location
order by state;

--12. display the average budget of the product where the avg budget margin greater then 100.
select productid,
avg(budget_margin) as avg_budget_margin
from fact
group by productid
having avg(budget_margin) >100;

--13. what is the total sales done on 2010-01-01
select date ,sum(sales) as total sales
from fact
where date = '2010-01-01'
group by date;

--14. Display the average total expense of each productid on an individual date.
select date,
	   sum(sales) as sales
from fact
group by date
order by date;

--15. Display the table with the following attributes- date,productid, producttype,product,sales,profit,state,areacode
select f.date,
	   f.productid,
	   p.product_type,
	   p.product,
	   f.sales,
	   f.profit,
	   f.area_code,
	   l.state
from fact as f
left join product as p
on f.productid = p.productid
left join location as l 
on f.area_code = l.area_code


--16. display the rank withour any gap to show the sales wise rank
select productid,
	   sum(sales)as total_sales,
	   rank() over(order by sum(sales))as rank
from fact 
group by productid

--17. find the state wise profit and sales
select sum(f.profit)as total_profit,
	   sum(f.sales)as total_sales,
	   l.state
from fact as f 
left join location as l
on f.area_code = l.area_code
group by state
order by state;

--18.find the state wise profit and sales along with product name 
select sum(f.profit)as total_profit,
	   sum(f.sales)as total_sales,
	   l.state,
	   p.product
from fact as f 
left join location as l
on f.area_code = l.area_code
left join product as p
on f.productid  = p.productid
group by product,state
order by state,product;

--19. if there is an increase in sales of 5% calculate the increased sales.
select * from fact

--20. find the maxmium profit along with the productid and product type.
select f.productid,max(f.profit) as max_profit,p.type
from fact as f
left join product as p 
on f.productid = p.productid
group by f.productid,p.type

--21. create Sp to fetch the result according to product type from product.
CREATE PROCEDURE product_inqu
@product_type nvarchar(50)
as
begin 
select * from product
where product_type = @product_type
end;

--search for product_type is tea
exec product_inqu @product_type = 'Tea';

--22. write a query by creating a condition in which if the total expenses is less than 60 then it is a profit or else loss.
select *,
case when total_expenses < 60 then 'profit'
else 'loss' 
end as P/L
from fact

--23. give the total weekly sales value with the data and productid details. use rollup to pull the data in herirarchial order.
SELECT datepart(week,date) as weeknumber,productid,
sum(sales) as total_weekly_sale
from fact
group by rollup(datepart(week,date),productid)

--24. apply union and intersection operator on the table which consist of attributes area code.
select area_code from fact 
union 
select area_code from location;

select area_code from fact
intersect
select area_code from location;

--25. create a user defined function for the product table to fetch a particular product type based upon the user's prefrence.
create function getproductdetails (
@product_type nvarchar(50)
)
returns table
as 
return
(
	select * from product
	where product_type = @product_type
	)
--to use the function
	select * from getproductdetails('coffee')

--26. change the product type from coffees to tea where productid is 1 and undo it.
begin transaction 
update product
set product_type =replace(product_type,'coffee','tea') 
where productid = 1;
--rollback transaction
rollback transaction

--27. display the date, product id and sales where total expenses are between 100 to 200.
select date,productid,sales from fact
where total_expenses between 100 and 200;

--28. delete the records in the product table for regular type.
delete from product
where product_type = 'Regular';

--29. display the ASCII value of the fifth character from column product. 
select productid,product_type,
ascii(substring(product_type,5,1)) as fifthchar
from product;




